---
title: "PredictBirdSpecies_NN"
author: "Radhika"
date: "5/10/2022"
output: github_document

---


```{r}
library(ggplot2)
library(tidyverse)
library(keras)
library(tensorflow)
library(reticulate)
```

```{r}
label_list <- dir("E:\\Radhika\\SU_MSDS\\Spring22Quarter\\DATA5332_StatML2\\DATA5322_Assignments\\DATA_5332_HW3\\train_small3")
output_n <- length(label_list)
save(label_list, file="label_list.R")
```
 
```{r}
width <- 224
height<- 224
target_size <- c(width, height)
rgb <- 3 #color channels
```

```{r}
path_train <- "E:\\Radhika\\SU_MSDS\\Spring22Quarter\\DATA5332_StatML2\\DATA5322_Assignments\\DATA_5332_HW3\\train_small3\\"
train_data_gen <- image_data_generator(rescale = 1/255, 
                  validation_split = .2)
```

```{r}
train_images <- flow_images_from_directory(path_train,
  train_data_gen,
  subset = 'training',
  target_size = target_size,
  class_mode = "categorical",
  shuffle=F,
  classes = label_list,
  seed = 2021)
```

```{r}
table(train_images$classes)
```

```{r}
validation_images <- flow_images_from_directory(path_train,
 train_data_gen, 
  subset = 'validation',
  target_size = target_size,
  class_mode = "categorical",
  classes = label_list,
  seed = 2021)
```
```{r}
plot(as.raster(train_images[[1]][[1]][17,,,]))
```

```{r}
mod_base <- application_xception(weights = 'imagenet', 
   include_top = FALSE, input_shape = c(width, height, 3))
freeze_weights(mod_base) 
```



```{r}
model_function <- function(learning_rate = 0.001, 
  dropoutrate=0.2, n_dense=1024){
  
  k_clear_session()
  
  model <- keras_model_sequential() %>%
    mod_base %>% 
    layer_global_average_pooling_2d() %>% 
    layer_dense(units = n_dense) %>%
    layer_activation("relu") %>%
    layer_dropout(dropoutrate) %>%
    layer_dense(units=output_n, activation="softmax")
  
  model %>% compile(
    loss = "categorical_crossentropy",
    optimizer = optimizer_adam(lr = learning_rate),
    metrics = "accuracy"
  )
  
  return(model)
  
}
```

```{r}
model <- model_function()
model
```

```{r}
batch_size <- 32
epochs <- 6
system.time(
  hist <- model %>% fit_generator(
    train_images,
    steps_per_epoch = train_images$n %/% batch_size, 
    epochs = epochs, 
    validation_data = validation_images,
    validation_steps = validation_images$n %/% batch_size,
    verbose = 2
  )
)
```

Evaluating and testing the model

```{r}
path_test <- "E:\\Radhika\\SU_MSDS\\Spring22Quarter\\DATA5332_StatML2\\DATA5322_Assignments\\DATA_5332_HW3\\test_small3\\"

test_data_gen <- image_data_generator(rescale = 1/255)

test_images <- flow_images_from_directory(path_test,
   test_data_gen,
   target_size = target_size,
   class_mode = "categorical",
   classes = label_list,
   shuffle = F,
   seed = 2021)

model %>% evaluate_generator(test_images, 
                     steps = test_images$n)
```
Testing on a random image

```{r}
test_image <- image_load("E:\\Radhika\\SU_MSDS\\Spring22Quarter\\DATA5332_StatML2\\DATA5322_Assignments\\DATA_5332_HW3\\barn_swallow_test.jpg",
                                  target_size = target_size)

x <- image_to_array(test_image)
x <- array_reshape(x, c(1, dim(x)))
x <- x/255
pred <- model %>% predict(x)
pred <- data.frame("Bird" = label_list, "Probability" = t(pred))
pred <- pred[order(pred$Probability, decreasing=T),][1:3,]
pred$Probability <- paste(format(100*pred$Probability,2),"%")
pred
```

```{r}
# Plot confusion matrix
#onfMat <- confusionMatrix(data = factor(predClass, levels = speciesClass),
 #                          reference = factor(trueClass, levels = speciesClass))
```

